from __future__ import annotations
from dataclasses import dataclass
import functools
from Options import Toggle, OptionSet
from typing import List, Dict, Set
from ..enums import KeymastersKeepGamePlatforms
from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

@dataclass
class PuzzLinkOptions:
    puzz_link_make_puzzles: PuzzLinkMakePuzzles

class PuzzLinkGame(Game):
    name = "puzz.link"
    platform = KeymastersKeepGamePlatforms.WEB
    platforms_other = []
    is_adult_only_or_unrated = False
    options_cls = PuzzLinkOptions

    all_games = [
        "aho",
        "akari",
        "akichi",
        "amibo",
        "angleloop",
        "anglers",
        "antmill",
        "aqre",
        "aquapelago",
        "aquarium",
        "araf",
        "armyants",
        "arrowflow",
        "arukone",
        "ayeheya",
        "balance",
        "balloon",
        "barns",
        "battleship",
        "bdblock",
        "bdwalk",
        "bonsan",
        "bosanowa",
        "bosnianroad",
        "box",
        "brownies",
        "bunnyhop",
        "canal",
        "castle",
        "cave",
        "cbanana",
        "cbblock",
        "chainedb",
        "chocona",
        "circlesquare",
        "cocktail",
        "coffeemilk",
        "cojun",
        "compass",
        "context",
        "coral",
        "country",
        "creek",
        "crossstitch",
        "cts",
        "curvedata",
        "dbchoco",
        "detour",
        "diamond",
        "disloop",
        "dominion",
        "doppelblock",
        "dosufuwa",
        "dotchi",
        "doubleback",
        "easyasabc",
        "evolmino",
        "factors",
        "familyphoto",
        "fillmat",
        "fillomino",
        "firefly",
        "firewalk",
        "fivecells",
        "forestwalk",
        "fourcells",
        "fracdiv",
        "geradeweg",
        "goishi",
        "gokigen",
        "guidearrow",
        "haisu",
        "hakoiri",
        "hanare",
        "hashi",
        "hebi",
        "herugolf",
        "heteromino",
        "heyablock",
        "heyabon",
        "heyawake",
        "hinge",
        "hitori",
        "icebarn",
        "icelom",
        "icelom2",
        "icewalk",
        "ichimaga",
        "ichimagam",
        "ichimagax",
        "interbd",
        "isowatari",
        "japanesesums",
        "juosan",
        "kaero",
        "kaidan",
        "kaisu",
        "kakuro",
        "kakuru",
        "kazunori",
        "keywest",
        "kinkonkan",
        "koburin",
        "kouchoku",
        "kramma",
        "kramman",
        "kropki",
        "kurarin",
        "kurochute",
        "kuroclone",
        "kurodoko",
        "kuromenbun",
        "kurotto",
        "kusabi",
        "ladders",
        "lapaz",
        "lightshadow",
        "lither",
        "lits",
        "lohkous",
        "lollipops",
        "lookair",
        "loopsp",
        "loute",
        "magnets",
        "makaro",
        "mannequin",
        "martini",
        "masyu",
        "maxi",
        "meander",
        "mejilink",
        "midloop",
        "minarism",
        "mines",
        "mintonette",
        "mirrorbk",
        "mochikoro",
        "mochinyoro",
        "moonsun",
        "mukkonn",
        "myopia",
        "nagare",
        "nagenawa",
        "nanameguri",
        "nanro",
        "nawabari",
        "news",
        "nibunnogo",
        "nikoji",
        "nondango",
        "nonogram",
        "norinori",
        "norinuri",
        "nothing",
        "nothree",
        "numlin",
        "numrope",
        "nuribou",
        "nurikabe",
        "nurimaze",
        "nurimisaki",
        "nuriuzu",
        "oneroom",
        "onsen",
        "ovotovata",
        "oyakodori",
        "paintarea",
        "parquet",
        "patchwork",
        "pencils",
        "pentatouch",
        "pentominous",
        "pentopia",
        "pipelink",
        "pipelinkr",
        "putteria",
        "ququ",
        "railpool",
        "rassi",
        "rectslider",
        "reflect",
        "remlen",
        "renban",
        "ringring",
        "ripple",
        "roma",
        "roundtrip",
        "sananko",
        "sashigane",
        "sashikazune",
        "sato",
        "scrin",
        "shakashaka",
        "shikaku",
        "shimaguni",
        "shugaku",
        "shwolf",
        "simplegako",
        "simpleloop",
        "skyscrapers",
        "slalom",
        "slashpack",
        "slitherlink",
        "snake",
        "snakeegg",
        "snakepit",
        "squarejam",
        "starbattle",
        "statuepark",
        "stostone",
        "sudoku",
        "sukoro",
        "sukororoom",
        "swslither",
        "symmarea",
        "tajmahal",
        "takoyaki",
        "tapa",
        "tapaloop",
        "tasquare",
        "tatamibari",
        "tateyoko",
        "tawa",
        "tentaisho",
        "tents",
        "teri",
        "tetrochain",
        "tetrominous",
        "tilecity",
        "tilepaint",
        "toichika",
        "toichika2",
        "tontonbeya",
        "tontti",
        "trainstations",
        "tren",
        "triplace",
        "tslither",
        "turnaround",
        "uramashu",
        "usoone",
        "usotatami",
        "view",
        "voxas",
        "vslither",
        "wafusuma",
        "wagiri",
        "walllogic",
        "waterwalk",
        "wblink",
        "wittgen",
        "yajikazu",
        "yajilin",
        "yajilin-regions",
        "yajisoko",
        "yajitatami",
        "yinyang",
        "yosenabe",
    ]

    popular_games = [
        "akari",
        "aqre",
        "cave",
        "dbchoco",
        "fillomino",
        "firefly",
        "hebi",
        "heyawake",
        "hitori",
        "icebarn",
        "kakuro",
        "lits",
        "masyu",
        "midloop",
        "moonsun",
        "norinori",
        "nurikabe",
        "pipelink",
        "reflect",
        "ringring",
        "sashigane",
        "shakashaka",
        "shikaku",
        "shugaku",
        "simpleloop",
        "slalom",
        "slitherlink",
        "starbattle",
        "tapa",
        "tentaisho",
        "yajikazu",
        "yajilin",
        "yajilin-regions",
    ]

    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        objectives = [
            GameObjectiveTemplate(
                label="Solve a difficulty DIFFICULTY puzzle",
                data={
                    "DIFFICULTY": ((1, 2, 3, 4), 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=8,
            ),
            GameObjectiveTemplate(
                label="Solve a difficulty 5 or unrated puzzle",
                data={
                },
                is_time_consuming=True,
                is_difficult=True,
                weight=8,
            ),
            GameObjectiveTemplate(
                label="Solve a difficulty DIFFICULTY puzzle of type TYPE",
                data={
                    "DIFFICULTY": ((1, 2, 3, 4), 1),
                    "TYPE": (self.popular_games, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=4,
            ),
            GameObjectiveTemplate(
                label="Solve a difficulty 5 or unrated puzzle of type TYPE",
                data={
                    "TYPE": (self.popular_games, 1),
                },
                is_time_consuming=True,
                is_difficult=True,
                weight=4,
            ),
            GameObjectiveTemplate(
                label="Solve a puzzle of type TYPE",
                data={
                    "TYPE": (self.all_games, 1),
                },
                is_time_consuming=False,
                is_difficult=False,
                weight=2,
            ),
            GameObjectiveTemplate(
                label="Solve a difficulty 5 or unrated puzzle of type TYPE",
                data={
                    "TYPE": (self.all_games, 1),
                },
                is_time_consuming=True,
                is_difficult=True,
                weight=2,
            ),
        ]

        if self.archipelago_options.puzz_link_make_puzzles:
            objectives.append(GameObjectiveTemplate(
                label="Create a puzzle of type TYPE",
                data={
                    "TYPE": (self.popular_games, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=2,
            ))
            objectives.append(GameObjectiveTemplate(
                label="Create a puzzle of type TYPE",
                data={
                    "TYPE": (self.all_games, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ))
        
        return objectives

class PuzzLinkMakePuzzles(Toggle):
    """If enabled, you may be asked to create puzzles."""
    display_name = "puzz.link make puzzles"
    default = 0
