from __future__ import annotations
from dataclasses import dataclass
import functools
from Options import Toggle, OptionSet
from typing import List, Dict, Set
from ..enums import KeymastersKeepGamePlatforms
from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

@dataclass
class SlayThePrincessOptions:
    pass

class SlayThePrincessGame(Game):
    name = "Slay The Princess - The Pristine Cut"
    platform = KeymastersKeepGamePlatforms.PC
    platforms_other = [KeymastersKeepGamePlatforms.SW, KeymastersKeepGamePlatforms.PS5, KeymastersKeepGamePlatforms.PS4, KeymastersKeepGamePlatforms.XONE, KeymastersKeepGamePlatforms.XSX]
    is_adult_only_or_unrated = False
    options_cls = SlayThePrincessOptions

    gallery_pages = (
        ('The Hero and the Princess', (
            "You're on a path in the woods...",
            'And at the end of that path is a cabin.',
            'And in the basement of that cabin...',
            'Is a Princess.',
            'Find the Tower.',
            'Find the Damsel.',
            'Find the Nightmare.',
            'Find the Prisoner.',
            'Find the Spectre.',
            'Find the Razor.',
            'Find the Witch.',
            'Find the Beast.',
            'Find the Adversary.',
            'Find the Stranger.',
            "I thought you said she wasn't armed!",
            'Get her to break her own chains.',
            'Always leave a means of easy egress.',
            'Everything would be so easy if you would just do exactly as I say as quickly as you can.',
        )),
        ('The Spaces Between', (
            "The 'woods.'",
            "the 'cabin.'",
            "It's you.",
            "You've grown.",
            "You've withered.",
            "You've unraveled.",
            'You are nothing at all.',
            'The Narrator.',
            'Damn both of you to an incomplete existence.',
        )),
        ('The End of Everything', (
            'Finish the game.',
            'Finish the game. [2]',
            'Find your freedom as gods forever.',
            'Find your freedom as gods forever. [2]',
            'Go back to where it all started.',
            'Go back to where it all started, and meet her face to face.',
            'The end is never the end is never the end.',
            'Return to your beginning and slay her once and for all.',
            'Leave with her, at the end of everything.',
            'Leave with her, at the end of everything. [2]',
            "Go back to where it all started. You always were a bit of a contrarian, weren't you?",
            "We don't think there's a way for us to leave, but maybe there doesn't have to be an ending.",
            "We want whatever might be on the other side of this door. Something new, that we'll experience together.",
            'Return to your strange beginning and slay her once and for all.',
            'The fruits of your labor. A world free from death.',
            'Destroy her. Without any outside help.',
            'Destroy her. Without any outside help. [2]',
            'Destroy her. Without any outside help. [3]',
            'Destroy her without any outside help. And then find your new world.',
            'Defeat her without any outside help, and then offer her grace.',
        )),
        ('The Adversary', (
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Ignore the whiners. If she blocks your attack, you just have to push harder.',
            "Heeeeeere's Princess!",
            'Die to her upstairs. Unarmed.',
            'Die to her upstairs. Armed.',
            'Witness her resurrection.',
            'Goad her into giving you a free shot, and then take it.',
            'Make an obscene gesture, possibly against your will.',
            'That which cannot die is that which cannot die is that which cannot die.',
            "You don't need a weapon to win a fight.",
            "Maybe you do need a weapon, but it's too late now.",
            "Hey, Princess... I didn't hear no bell.",
            "Sometimes you have to try and free people even if they don't realize they want to be free.",
            'Agility is the only way to overcome brute strength.',
            "It's not a fight if you refuse to strike back.",
            "It's not a fight if you refuse to strike back. [2]",
            "You've been here before.",
            'A bold heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Tower', (
            'More like a temple than a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Resist a god through force of arms.',
            'Resist a god through force of arms, but ultimately succumb.',
            'Try to resist a god purely through force of will. No weapons.',
            'Free a god to bring about the end of everything.',
            'Free a god to bring about the end of everything. [2]',
            'Fell a god.',
            'Fell a god. [2]',
            'Fell a god. [3]',
            "You've been here before.",
            'An overwhelming heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Spectre', (
            "It's been a long time since anyone's been here, hasn't it?",
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Meet the Spectre.',
            'Let a spirit into your home.',
            'Let a spirit into your home. [2]',
            'Free a lost soul.',
            'Free a lost soul. [2]',
            'Free a lost soul. [3]',
            'Provoke an angry spirit.',
            'Provoke an angry spirit. [2]',
            'Take on a spirit and exorcise it from your body.',
            'Take on a spirit and exorcise it from your body. [2]',
            'A spirit checks for a pulse.',
            'Attack a spirit with cold steel. No hesitation.',
            'Abandon a spirit to its torment.',
            "You've been here before.",
            'A yearning heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Nightmare', (
            'Why does nobody ever mention the eyes?',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Meet your nightmare.',
            'Set your nightmare loose upon the world.',
            'Set your nightmare loose upon the world. [2]',
            'Set your nightmare loose upon the world. [3]',
            'Set your nightmare loose upon the world. [4]',
            'Get shoved into a bottomless pit.',
            'Get shoved into a bottomless pit. [2]',
            'Slay your only exit.',
            "See what's behind the mask.",
            "See what's behind the mask. [2]",
            "See what's behind the mask. [3]",
            "See what's behind the mask. [4]",
            "See what's behind the mask. [5]",
            "See what's behind the mask. [6]",
            "You've been here before.",
            'A tender heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Razor', (
            'What a mess.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'But her hands were behind her back!',
            "Okay. I'm bored.",
            "She said she wasn't armed. So what's the harm in getting a little closer?",
            "Now hold on... these aren't the woods.",
            'What... is this place? This is not the same cabin.',
            'Meet her. Again.',
            'Call an ambulance... but not for me!',
            'Make her blush.',
            "You've lost track of yourself, haven't you?",
            "This isn't even my final form.",
            'Meet a mutual end.',
            'Empty your mind. Be formless. Shapeless. Like water.',
            'Empty your mind. Be formless. Shapeless. Like water. [2]',
            "You've been here before, this time with a cage of iron.",
            'A piercing heart in a cage of iron.',
            "You've been here before, this time with a heart beating free.",
            'A piercing heart beating free.',
            'See through her eyes at the end of everything.',
        )),
        ('The Beast', (
            "This cabin's seen better days, hasn't it?",
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Get swallowed up by the beast.',
            'Make your way to her heart and end this.',
            'Free her.',
            'Fight her to the death.',
            'Fight her to the death. [2]',
            'Fight her to the death. [3]',
            'What great big eyes you have.',
            'Dodge.',
            'Dodge again.',
            'Dodge until you can dodge no longer.',
            'That hurt. Are you just the cornered animal you seem to be, or could you be a rival?',
            "I didn't mean to do that. I still need to devour you, and it doesn't count if you're dead..",
            "You've been here before.",
            'A cunning heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Witch', (
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Make a peace offering to someone you betrayed.',
            'Fight dirty in a direct confrontation.',
            'Fight dirty in a direct confrontation. [2]',
            'Fight dirty in a direct confrontation. [3]',
            'Fight dirty in a direct confrontation. [4]',
            'Fight her until the world itself swallows you up.',
            'Fight her until the world itself swallows you up. [2]',
            'One of you has to go first. Might as well be you.',
            'One of you was always going to betray the other. Might as well be you doing the betraying.',
            "You're not turning your back to her.",
            "You're not turning your back to her. [2]",
            "You're not turning your back to her. [3]",
            "You're not turning your back to her. [4]",
            'The entire cabin is collapsing around you. Maybe the two of you should stop fighting?',
            "You've been here before.",
            'A righteous heart.',
            'See through her broken eyes at the end of everything.',
            'See through her confident eyes at the end of everything.',
        )),
        ('The Stranger', (
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'And at the center of it all is something that can only be described as...',
            'What— what the hell was that?! What happened to us?',
            "Split her as much as you're able.",
            'To be everything is to be nothing at all.',
            'To be everything is to be nothing at all. [2]',
            'To be everything is to be nothing at all. [3]',
            'To be everything is to be nothing at all. [4]',
            "You've been here before.",
            'A rich and vibrant heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Prisoner', (
            'A prison. Just like it should be.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            "I'm not locked in here with you. We're both locked in here together.",
            "I'm not locked in here with you. We're both locked in here together. [2]",
            "I'm not locked in here with you. We're both locked in here together. [3]",
            "I'm not locked in here with you. We're both locked in here together. [4]",
            "What could go wrong with handing her your weapon? She's locked up.",
            'Successfully free her.',
            'Enter a violent confrontation.',
            'Enter a violent confrontation. [2]',
            'Slay her.',
            "Receive vital evidence of the Princess' wrongdoings.",
            "You've been here before, and now you're here again. Whole.",
            'A patient heart.',
            "You've been here before, and now you're here again. But this time without a head.",
            'A clever heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Damsel', (
            'A prison fitting a royal prisoner.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'Free her from her bindings.',
            'Free her from her bindings. [2]',
            'Leave with her.',
            'Leave with her. [2]',
            'Leave with her. [3]',
            'Is it just me or is she... changing?',
            "No, she's not just changing, she's becoming worse.",
            'Really worse.',
            'Oh no.',
            'Slay her.',
            "She's changing. You have to slay her. Now!",
            "She's changing. You have to slay her. Now! [2]",
            "She's changing. You have to slay her. Now! [3]",
            "Give her everything she didn't know she wanted.",
            "You've been here before.",
            'A gentle heart.',
            'A pliable heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Eye of the Needle', (
            "These aren't the same woods.",
            "And this isn't the same cabin.",
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'The only mistake you made last time was not pushing yourself hard enough.',
            'The only mistake you made last time was not pushing yourself hard enough. [2]',
            'Give chase. The only way out is through the eye of the needle.',
            'Give chase. The only way out is through the eye of the needle. [2]',
            'Thread the eye of the needle and slay her once and for all.',
            'Thread the eye of the needle and slay her once and for all. [2]',
            'Thread the eye of the needle and slay her once and for all. [3]',
            'Thread the eye of the needle and slay her once and for all. [4]',
            'Thread the eye of the needle and slay her once and for all. [5]',
            'With a skeptic companion, thread the eye of the needle and lead her to the other side.',
            'Give chase, but fail to thread the eye of the needle.',
            'Give chase, but fail to thread the eye of the needle. [2]',
            'Give chase, but fail to thread the eye of the needle. [3]',
            "You've been here before.",
            'A burning heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Fury', (
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'You are deconstructed. You are reconstructed.',
            'The ball is unraveled into the shape of a body.',
            'The blade is still here, even after everything.',
            'Give her your hand.',
            "I feel so cold. Is it because you're gone?",
            "If only you could remember what I remember. If only you weren't so weak.",
            'A towering heart wounded and alone. One that is familiar to you, if distant.',
            "What are you? You're clearly not your skin.",
            "Come on. One more step. Do hit! Hit me! Show me what you're made of!",
            'Preserved, perfectly, in the amber of her torment.',
            "It's not over. We're a god killer. We've returned from death itself twice.",
            'Now, little bird, what was it you wanted to tell me?',
            "Let's see what meaning we can find together. Let's see what we're made of.",
            "We don't need to count anymore.",
            'And then the forces disappear. The bonds holding your cells together break.',
            'A weathered heart.',
            'A weathered heart, held in ribbons.',
            'See through her eyes at the end of everything.',
        )),
        ('The Apotheosis', (
            'Oh, let me guess! And as the end of the path... is a cabin!',
            'This is how it always was going to end, and this is how it always was going to begin.',
            "Do it, then. Show me what you think it takes to end what's destined to end everything.",
            'Allow an ungrounded voice to tap into your potential.',
            "Walk the razor's edge between courage and madness.",
            'Overpower a psychic barrier.',
            'Make her feel what you have felt.',
            'Her touch is soft.',
            'Carve into her divine heart.',
            'Gift a spiteful reminder to an arrogant god.',
            'Watch as the kindling of your soul burns to ash.',
            'We could have had everything.',
            "If only you'd given me a little more.",
            'What remnant of the old could possibly be left to defy me?',
            'She is drowning.',
            'I am sorry.',
            'Fly, little bird.',
            "You've been here before.",
            'A terrifying and divine heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Princess and the Dragon', (
            "So that's you.",
            "There has to be something for you to do other than wait, but that won't stop you from waiting as long as you can.",
            'Observe your new form.',
            'A figure emerges, shrouded in a feathered darkness, the world trailing behind it.',
            'Reveal your identity to some old friends. A brash enough host might do this for you.',
            'Keep your identity hidden from some old friends. Might require a more receptive host.',
            'Abandon a gentle companion to her fate.',
            'What once was one, then was two...',
            'And then was one again.',
            "Welcome back! I'm so disappointed in you.",
            'Fail to disarm a harsh companion.',
            "Welcome back! Life is all about taking the easy wins, isn't it?",
            'Attempt to free a gentle companion on your own.',
            'Leave with a harsh companion.',
            'Leave with a gentle companion.',
            'Step into your freedom, together.',
            "You've been here before.",
            'An empathetic heart.',
            'An empathetic heart, held in stencil.',
            'See through her eyes at the end of everything.',
        )),
        ('The Wraith', (
            "These aren't the same woods.",
            "And this isn't the same cabin.",
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'You are nothing but a passenger.',
            'Set your demons loose upon the world.',
            "You're the only prison that can hold your demons.",
            'There is no choice here. She will take what she is owed.',
            "You've been here before.",
            'A driven heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Moment of Clarity', (
            "These aren't the same woods.",
            "And this isn't the same cabin.",
            "You're just an object.",
            'A tool.',
            'You once were something else, a long time ago.',
            'But was that something you?',
            'Or is it just a dull and jaded memory?',
            'There is no other ending here.',
            'Just take her hand and set her free.',
            'For all her past cruelties, the moment feels gentle, tender even.',
            "And that's the end! I wonder what we're going to do next.",
            "You've been here before.",
            'A wise heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Den', (
            'The woods are... denser than I remember them.',
            'Maybe this used to be a cabin.',
            'To be torn between thought and action is to hesitate. And to hesitate is to die.',
            'Reject instinct. Fight her to the end.',
            'Reject instinct. Fight her to the end. [2]',
            'Give yourself to instinct.',
            'To consume is to become.',
            "Now that's she's stuck, there's nothing stopping you from ending this.",
            'I told you not to flinch, I told you.',
            'Your work is done. Leave her to starve.',
            'Wait in silence for your end.',
            "Maybe there's more to her than we thought.",
            'Your mouths are full of dirt.',
            'She has left you to die.',
            'Are we free?',
            'Reach the crossroads of will and instinct.',
            'What once was you, now is me.',
            "You've been here before.",
            'A ravenous heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Wild', (
            'We are a path in the woods.',
            'A glimpse of freedom.',
            'Gaze into the heart of darkness.',
            "Separate doesn't mean over.",
            "Separate doesn't mean over. [2]",
            'Separate before ending it all.',
            "You've been here before, and now you're back. Even if you've been separated by forces beyond your will.",
            'A curious and beautiful heart.',
            "You've been here before. This time you've carried a wound.",
            'A scarred and beautiful heart.',
            'See through her woven eyes at the end of everything.',
            'See through her wounded eyes at the end of everything.',
        )),
        ('The Thorn', (
            "These aren't the same woods.",
            "And this isn't the same cabin.",
            'I thought this was supposed to be a cabin.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            "Strike at a thorny rose's heart.",
            'Share a thorny prison of your own making.',
            "She's going to swallow it out of spite, isn't she?",
            'Turn over a new leaf and learn to trust again.',
            'Turn over a new leaf and learn to trust again. [2]',
            'Turn over a new leaf and learn to trust again. [3]',
            'Turn over a new leaf and learn to trust again. [4]',
            'Turn over a new leaf and learn to trust again. [5]',
            'Turn over a new leaf and learn to trust again. [6]',
            'Turn over a new leaf and learn to trust again. [7]',
            'Kiss the girl.',
            'Kiss the girl. [2]',
            "You've been here before.",
            'A cautious heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Cage', (
            "These aren't the same woods. We must be getting closer.",
            'Because getting to the cabin was too easy last time.',
            'If the Princess lives here, slaying her would probably be doing her a favor.',
            'You make out a figure standing in the gloom, obscured in shadow.',
            'You give me your implement. See? You already did that part.',
            "This is all getting so predictable, isn't it? Pop.",
            "You only ever thought you were in control. Isn't it so much nicer to let go?",
            "You only ever thought you were in control. Isn't it so much nicer to let go? [2]",
            "You only ever thought you were in control. Isn't it so much nicer to let go? [3]",
            'Both hers and yours collapse, their dance complete.',
            'A peace offering.',
            'The things we leave behind.',
            'At the edge of freedom.',
            "It's a little cold out here, isn't it?",
            "All of that, just to take it all away. You're cold.",
            'I cut myself free.',
            'I cut myself free. [2]',
            "You've been here before.",
            'An open or watchful heart.',
            'See through her eyes at the end of everything.',
        )),
        ('The Grey', (
            "These aren't the same woods. It wasn't raining before.",
            "These aren't the same woods as before. They're more of a rolling plain.",
            'I can smell the wood rot.',
            'More of a museum than a cabin.',
            'A drowned body.',
            'A desiccated body.',
            'Burning down the house.',
            'What the water gave me.',
            'Burning down the house. [2]',
            'What the water gave me. [2]',
            'Burning down the house. [3]',
            'What the water gave me. [3]',
            'Burning down the house. [4]',
            'Burning down the house. [5]',
            "You've been here before the flames took it all away.",
            'A bright heart.',
            "You've been here before the flood took it all away.",
            'A deep heart.',
            'See through her burning eyes at the end of everything.',
            'See through her drowned eyes at the end of everything.',
        )),
        ('Happily Ever After', (
            "Mate, we're clearly already in the cabin.",
            "If the Princess lives here, slaying her would probably... agh, no that's not right.",
            'Deduce the identity of the shadow with the help of a questioning voice.',
            "Dinner's ready.",
            'Finish playing a game with the help of a manipulative voice.',
            'Keep the last flame lit. Forever.',
            "An important part of me is gone, but I'm still here.",
            "It's finally over.",
            'Offer her your hand.',
            'There might be worse things than the end of the world.',
            'Leave with her, hand not in hand.',
            'I meant it, when I said I wanted to dance.',
            'I meant it, when I said I wanted to dance. [2]',
            'I meant it, when I said I wanted to dance. [3]',
            'I meant it, when I said I wanted to dance. [4]',
            'I meant it, when I said I wanted to dance. [5]',
            "You've been here before.",
            'An honest heart.',
            'See through her seated eyes at the end of everything.',
            'See through her eyes at the end of everything as you dance under the stars.',
        )),
    )

    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        objectives = []
        for (category, goals) in self.gallery_pages:
            if category == 'The End of Everything':
                objectives.append(GameObjectiveTemplate(
                    label=f'{category}: GOAL',
                    data={'GOAL': (goals, 1)},
                    is_time_consuming=True,
                    is_difficult=False,
                    weight=len(goals),
                ))
            else:
                non_end_goals = [x for x in goals if 'end of everything' not in x]
                objectives.append(GameObjectiveTemplate(
                    label=f'{category}: GOAL',
                    data={'GOAL': (non_end_goals, 1)},
                    is_time_consuming=False,
                    is_difficult=False,
                    weight=len(non_end_goals),
                ))
                end_goals = [x for x in goals if 'end of everything' in x]
                if end_goals:
                    objectives.append(GameObjectiveTemplate(
                        label=f'{category}: GOAL',
                        data={'GOAL': (end_goals, 1)},
                        is_time_consuming=True,
                        is_difficult=False,
                        weight=len(end_goals),
                    ))
        
        return objectives

